class Movie {
  String title;
  String year;
  String rated;
  String released;
  String runtime;
  String genre;
  String director;
  String writer;
  String actors;
  String plot;
  String language;
  String country;
  String awards;
  String poster;
  String metascore;
  String imdbRating;
  String imdbVotes;
  String imdbID;
  String type;
  String response;
  var images = [];

  Movie(
    this.title,
    this.year,
    this.rated,
    this.released,
    this.runtime,
    this.genre,
    this.director,
    this.writer,
    this.actors,
    this.plot,
    this.language,
    this.country,
    this.awards,
    this.poster,
    this.metascore,
    this.imdbRating,
    this.imdbVotes,
    this.imdbID,
    this.type,
    this.response,
    this.images,
  );

  static List<Movie> movies = [
    Movie(
      "Avatar",
      "2009",
      "PG-13",
      "18 Dec 2009",
      "162 min",
      "Action, Adventure, Fantasy",
      "James Cameron",
      "James Cameron",
      "Sam Worthington, Zoe Saldana, Sigourney Weaver, Stephen Lang",
      "A paraplegic marine dispatched to the moon Pandora on a unique mission becomes torn between following his orders and protecting the world he feels is his home.",
      "English, Spanish",
      "USA, UK",
      "Won 3 Oscars. Another 80 wins & 121 nominations.",
      "http://ia.media-imdb.com/images/M/MV5BMTYwOTEwNjAzMl5BMl5BanBnXkFtZTcwODc5MTUwMw@@._V1_SX300.jpg",
      "83",
      "7.9",
      "890,617",
      "tt0499549",
      "movie",
      "True",
      [
        "https://images-na.ssl-images-amazon.com/images/M/MV5BMjEyOTYyMzUxNl5BMl5BanBnXkFtZTcwNTg0MTUzNA@@._V1_SX1500_CR0,0,1500,999_AL_.jpg",
        "https://images-na.ssl-images-amazon.com/images/M/MV5BMjEyOTYyMzUxNl5BMl5BanBnXkFtZTcwNTg0MTUzNA@@._V1_SX1500_CR0,0,1500,999_AL_.jpg",
        "https://images-na.ssl-images-amazon.com/images/M/MV5BMjEyOTYyMzUxNl5BMl5BanBnXkFtZTcwNTg0MTUzNA@@._V1_SX1500_CR0,0,1500,999_AL_.jpg",
      ],
    ),
    Movie(
      "shrunk",
      "2009",
      "PG-13",
      "18 Dec 2009",
      "162 min",
      "Action, Adventure, Fantasy",
      "James Cameron",
      "James Cameron",
      "Sam Worthington, Zoe Saldana, Sigourney Weaver, Stephen Lang",
      "A paraplegic marine dispatched to the moon Pandora on a unique mission becomes torn between following his orders and protecting the world he feels is his home.",
      "English, Spanish",
      "USA, UK",
      "Won 3 Oscars. Another 80 wins & 121 nominations.",
      "http://ia.media-imdb.com/images/M/MV5BMTYwOTEwNjAzMl5BMl5BanBnXkFtZTcwODc5MTUwMw@@._V1_SX300.jpg",
      "83",
      "7.9",
      "890,617",
      "tt0499549",
      "movie",
      "True",
      [
        "https://c4.wallpaperflare.com/wallpaper/783/578/361/exodus-gods-and-kings-poster-wallpaper-preview.jpg",
        "https://c4.wallpaperflare.com/wallpaper/783/578/361/exodus-gods-and-kings-poster-wallpaper-preview.jpg",
        "https://c4.wallpaperflare.com/wallpaper/783/578/361/exodus-gods-and-kings-poster-wallpaper-preview.jpg",
      ],
    ),
    Movie(
      "Avatar",
      "2009",
      "PG-13",
      "18 Dec 2009",
      "162 min",
      "Action, Adventure, Fantasy",
      "James Cameron",
      "James Cameron",
      "Sam Worthington, Zoe Saldana, Sigourney Weaver, Stephen Lang",
      "A paraplegic marine dispatched to the moon Pandora on a unique mission becomes torn between following his orders and protecting the world he feels is his home.",
      "English, Spanish",
      "USA, UK",
      "Won 3 Oscars. Another 80 wins & 121 nominations.",
      "http://ia.media-imdb.com/images/M/MV5BMTYwOTEwNjAzMl5BMl5BanBnXkFtZTcwODc5MTUwMw@@._V1_SX300.jpg",
      "83",
      "7.9",
      "890,617",
      "tt0499549",
      "movie",
      "True",
      [
        "https://i.ytimg.com/vi/qkJ_b0BEuQQ/movieposter.jpg",
        "https://i.ytimg.com/vi/qkJ_b0BEuQQ/movieposter.jpg",
        "https://i.ytimg.com/vi/qkJ_b0BEuQQ/movieposter.jpg",
      ],
    ),
    Movie(
      "Screaming",
      "2009",
      "PG-13",
      "18 Dec 2009",
      "162 min",
      "Action, Adventure, Fantasy",
      "James Cameron",
      "James Cameron",
      "Sam Worthington, Zoe Saldana, Sigourney Weaver, Stephen Lang",
      "A paraplegic marine dispatched to the moon Pandora on a unique mission becomes torn between following his orders and protecting the world he feels is his home.",
      "English, Spanish",
      "USA, UK",
      "Won 3 Oscars. Another 80 wins & 121 nominations.",
      "http://ia.media-imdb.com/images/M/MV5BMTYwOTEwNjAzMl5BMl5BanBnXkFtZTcwODc5MTUwMw@@._V1_SX300.jpg",
      "83",
      "8.9",
      "890,617",
      "tt0499549",
      "movie",
      "True",
      [
        "https://wallpaperaccess.com/full/1922937.jpg",
        "https://wallpaperaccess.com/full/1922937.jpg",
        "https://wallpaperaccess.com/full/1922937.jpg",
      ],
    ),
    Movie(
      "Scret",
      "2009",
      "PG-13",
      "18 Dec 2009",
      "162 min",
      "Action, Adventure, Fantasy",
      "James Cameron",
      "James Cameron",
      "Sam Worthington, Zoe Saldana, Sigourney Weaver, Stephen Lang",
      "A paraplegic marine dispatched to the moon Pandora on a unique mission becomes torn between following his orders and protecting the world he feels is his home.",
      "English, Spanish",
      "USA, UK",
      "Won 3 Oscars. Another 80 wins & 121 nominations.",
      "http://ia.media-imdb.com/images/M/MV5BMTYwOTEwNjAzMl5BMl5BanBnXkFtZTcwODc5MTUwMw@@._V1_SX300.jpg",
      "83",
      "7.3",
      "890,617",
      "tt0499549",
      "movie",
      "True",
      [
        "https://wallpaperaccess.com/full/1922943.jpg",
        "https://wallpaperaccess.com/full/1922943.jpg",
        "https://wallpaperaccess.com/full/1922943.jpg",
      ],
    ),
    Movie(
      "Good people",
      "2009",
      "PG-13",
      "18 Dec 2009",
      "162 min",
      "Action, Adventure, Fantasy",
      "James Cameron",
      "James Cameron",
      "Sam Worthington, Zoe Saldana, Sigourney Weaver, Stephen Lang",
      "A paraplegic marine dispatched to the moon Pandora on a unique mission becomes torn between following his orders and protecting the world he feels is his home.",
      "English, Spanish",
      "USA, UK",
      "Won 3 Oscars. Another 80 wins & 121 nominations.",
      "http://ia.media-imdb.com/images/M/MV5BMTYwOTEwNjAzMl5BMl5BanBnXkFtZTcwODc5MTUwMw@@._V1_SX300.jpg",
      "83",
      "7.7",
      "890,617",
      "tt0499549",
      "movie",
      "True",
      [
        "https://images-na.ssl-images-amazon.com/images/M/MV5BMjEyOTYyMzUxNl5BMl5BanBnXkFtZTcwNTg0MTUzNA@@._V1_SX1500_CR0,0,1500,999_AL_.jpg",
        "https://images-na.ssl-images-amazon.com/images/M/MV5BMjEyOTYyMzUxNl5BMl5BanBnXkFtZTcwNTg0MTUzNA@@._V1_SX1500_CR0,0,1500,999_AL_.jpg",
        "https://images-na.ssl-images-amazon.com/images/M/MV5BMjEyOTYyMzUxNl5BMl5BanBnXkFtZTcwNTg0MTUzNA@@._V1_SX1500_CR0,0,1500,999_AL_.jpg",
      ],
    ),
    Movie(
      "dump",
      "2009",
      "PG-13",
      "18 Dec 2009",
      "162 min",
      "Action, Adventure, Fantasy",
      "James Cameron",
      "James Cameron",
      "Sam Worthington, Zoe Saldana, Sigourney Weaver, Stephen Lang",
      "A paraplegic marine dispatched to the moon Pandora on a unique mission becomes torn between following his orders and protecting the world he feels is his home.",
      "English, Spanish",
      "USA, UK",
      "Won 3 Oscars. Another 80 wins & 121 nominations.",
      "http://ia.media-imdb.com/images/M/MV5BMTYwOTEwNjAzMl5BMl5BanBnXkFtZTcwODc5MTUwMw@@._V1_SX300.jpg",
      "83",
      "7.1",
      "890,617",
      "tt0499549",
      "movie",
      "True",
      [
        "https://c4.wallpaperflare.com/wallpaper/783/578/361/exodus-gods-and-kings-poster-wallpaper-preview.jpg",
        "https://c4.wallpaperflare.com/wallpaper/783/578/361/exodus-gods-and-kings-poster-wallpaper-preview.jpg",
        "https://c4.wallpaperflare.com/wallpaper/783/578/361/exodus-gods-and-kings-poster-wallpaper-preview.jpg",
      ],
    ),
    Movie(
      "God Father",
      "2009",
      "PG-13",
      "18 Dec 2009",
      "162 min",
      "Action, Adventure, Fantasy",
      "James Cameron",
      "James Cameron",
      "Sam Worthington, Zoe Saldana, Sigourney Weaver, Stephen Lang",
      "A paraplegic marine dispatched to the moon Pandora on a unique mission becomes torn between following his orders and protecting the world he feels is his home.",
      "English, Spanish",
      "USA, UK",
      "Won 3 Oscars. Another 80 wins & 121 nominations.",
      "http://ia.media-imdb.com/images/M/MV5BMTYwOTEwNjAzMl5BMl5BanBnXkFtZTcwODc5MTUwMw@@._V1_SX300.jpg",
      "83",
      "7.9",
      "890,617",
      "tt0499549",
      "movie",
      "True",
      [
        "https://i.ytimg.com/vi/qkJ_b0BEuQQ/movieposter.jpg",
        "https://i.ytimg.com/vi/qkJ_b0BEuQQ/movieposter.jpg",
        "https://i.ytimg.com/vi/qkJ_b0BEuQQ/movieposter.jpg",
      ],
    ),
    Movie(
      "shank shunk",
      "2009",
      "PG-13",
      "18 Dec 2009",
      "162 min",
      "Action, Adventure, Fantasy",
      "James Cameron",
      "James Cameron",
      "Sam Worthington, Zoe Saldana, Sigourney Weaver, Stephen Lang",
      "A paraplegic marine dispatched to the moon Pandora on a unique mission becomes torn between following his orders and protecting the world he feels is his home.",
      "English, Spanish",
      "USA, UK",
      "Won 3 Oscars. Another 80 wins & 121 nominations.",
      "http://ia.media-imdb.com/images/M/MV5BMTYwOTEwNjAzMl5BMl5BanBnXkFtZTcwODc5MTUwMw@@._V1_SX300.jpg",
      "83",
      "7.9",
      "890,617",
      "tt0499549",
      "movie",
      "True",
      [
        "https://wallpaperaccess.com/full/1922937.jpg",
        "https://wallpaperaccess.com/full/1922937.jpg",
        "https://wallpaperaccess.com/full/1922937.jpg",
      ],
    ),
    Movie(
      "king",
      "2009",
      "PG-13",
      "18 Dec 2009",
      "162 min",
      "Action, Adventure, Fantasy",
      "James Cameron",
      "James Cameron",
      "Sam Worthington, Zoe Saldana, Sigourney Weaver, Stephen Lang",
      "A paraplegic marine dispatched to the moon Pandora on a unique mission becomes torn between following his orders and protecting the world he feels is his home.",
      "English, Spanish",
      "USA, UK",
      "Won 3 Oscars. Another 80 wins & 121 nominations.",
      "http://ia.media-imdb.com/images/M/MV5BMTYwOTEwNjAzMl5BMl5BanBnXkFtZTcwODc5MTUwMw@@._V1_SX300.jpg",
      "83",
      "7.9",
      "890,617",
      "tt0499549",
      "movie",
      "True",
      [
        "https://wallpaperaccess.com/full/1922943.jpg",
        "https://wallpaperaccess.com/full/1922943.jpg",
        "https://wallpaperaccess.com/full/1922943.jpg",
      ],
    ),
  ];
}
